-- INNER JOIN
SELECT *
FROM BTCTB001_USUARIO TU
INNER JOIN BTCTB003_RESERVA TR ON TR.ID_USUARIO = TU.ID_USUARIO
INNER JOIN BTCTB002_DESTINO TD ON TD.ID_DESTINO = TR.ID_DESTINO;

-- LEFT JOIN
SELECT *
FROM BTCTB001_USUARIO TU
LEFT JOIN BTCTB003_RESERVA TR ON TR.ID_USUARIO = TU.ID_USUARIO;  -- Retorna null caso o usuário não tenha reserva

-- RIGHT JOIN
SELECT *
FROM BTCTB003_RESERVA TR
RIGHT JOIN BTCTB002_DESTINO TD ON TR.ID_DESTINO = TD.ID_DESTINO;  -- Retorna os destinos e null nos dados de reserva, senão tiver reserva

-- SUBCONSULTAS

SELECT * FROM BTCTB002_DESTINO
WHERE ID_DESTINO NOT IN (
	SELECT ID_DESTINO
    FROM BTCTB003_RESERVA
); -- Destino sem reserva

SELECT * FROM BTCTB001_USUARIO
WHERE ID_USUARIO NOT IN (
	SELECT ID_USUARIO
    FROM BTCTB003_RESERVA
); -- Usuário sem reserva

SELECT
	NO_USUARIO
,	(SELECT 
		COUNT(*)
	FROM BTCTB003_RESERVA
    WHERE ID_USUARIO = BTCTB001_USUARIO.ID_USUARIO) AS TOTAL_RESERVAS
FROM BTCTB001_USUARIO;




				