# Funções agregadas e group by
SELECT
	COUNT(*) AS TOTAL_USUARIOS
FROM BTCTB001_USUARIO;

SELECT
	COUNT(*) AS TOTAL_USUARIOS_RESERVADOS
FROM BTCTB001_USUARIO TU
INNER JOIN BTCTB003_RESERVA TR ON TR.ID_USUARIO = TU.ID_USUARIO;

# TIMESTAMPDIFF
SELECT
	MAX(TIMESTAMPDIFF(YEAR, DT_NASCIMENTO, CURRENT_DATE())) AS USUARIO_MAIS_VELHO
FROM BTCTB001_USUARIO;

--
# GROUP BY
SELECT TD.NO_DESTINO, COUNT(*)
FROM BTCTB003_RESERVA TR
INNER JOIN BTCTB002_DESTINO TD ON TD.ID_DESTINO = TR.ID_DESTINO
GROUP BY TD.ID_DESTINO;

--
# ORDER BY
SELECT TD.NO_DESTINO, COUNT(*) AS QTD_RESERVAS
FROM BTCTB003_RESERVA TR
INNER JOIN BTCTB002_DESTINO TD ON TD.ID_DESTINO = TR.ID_DESTINO
GROUP BY TD.ID_DESTINO
ORDER BY QTD_RESERVAS;

