DROP DATABASE IF EXISTS DB_BOOTCAMP;
CREATE DATABASE DB_BOOTCAMP;
USE DB_BOOTCAMP;

CREATE TABLE BTCTB001_USUARIO
(
	ID_USUARIO INT AUTO_INCREMENT COMMENT 'Identificador único serial do usuário'
,	NO_USUARIO VARCHAR(200) NOT NULL COMMENT 'Nome do usuário'
,	EE_USUARIO VARCHAR(100) NOT NULL COMMENT 'E-mail do usuário'
,	ED_USUARIO VARCHAR(100) NOT NULL COMMENT 'Endereço do usuário'
,	DT_NASCIMENTO DATE	NOT NULL COMMENT 'Data de nascimento do usuário'
,	CONSTRAINT PK_BTCTB001 PRIMARY KEY (ID_USUARIO)
,	CONSTRAINT UK01_BTCTB001 UNIQUE (NO_USUARIO,EE_USUARIO)
) COMMENT = 'Tabela de usuário';

CREATE TABLE BTCTB002_DESTINO
(
	ID_DESTINO INT AUTO_INCREMENT COMMENT 'Identificador único serial do destino'
,	NO_DESTINO VARCHAR(200) NOT NULL COMMENT 'Nome do destino'
,	DS_DESTINO VARCHAR(255) NOT NULL COMMENT 'Descrição do destino'
,	CONSTRAINT PK_BTCTB002 PRIMARY KEY (ID_DESTINO)
,	CONSTRAINT UK01_BTCTB002 UNIQUE (NO_DESTINO)
)COMMENT = 'Tabela de destino';

CREATE TABLE BTCTB003_RESERVA
(
	ID_RESERVA INT AUTO_INCREMENT COMMENT 'Identificador único serial da reserva'
,	ID_USUARIO INT COMMENT 'Referência ao ID do usuário que fez a reserva'
,	ID_DESTINO INT COMMENT 'Referência ao ID  do destino da reserva'
,	DT_RESERVA	DATE COMMENT 'Data da reserva'
,	IC_SITUACAO	CHAR(2)	DEFAULT 'PE' COMMENT 'Status da reserva (CO - Confirmada, PE - Pendente, CA - Cancelada)'
,	CONSTRAINT PK_BTCTB003 PRIMARY KEY (ID_RESERVA)
,	CONSTRAINT FK01_BTCTB001_BTCTB003 FOREIGN KEY (ID_USUARIO)
		REFERENCES BTCTB001_USUARIO(ID_USUARIO)
		ON DELETE CASCADE
,	CONSTRAINT FK02_BTCTB002_BTCTB003 FOREIGN KEY (ID_DESTINO)
		REFERENCES BTCTB002_DESTINO (ID_DESTINO)
        ON DELETE CASCADE
,	CONSTRAINT CC01_BTCTB003 CHECK (IC_SITUACAO IN ('PE','CO','CA'))
)COMMENT = 'Tabela de reserva';