# Caso já não tivesse implementado as PKs e FKs
ALTER TABLE BTCTB001_USUARIO
	MODIFY COLUMN ID_USUARIO INT AUTO_INCREMENT,
    ADD CONSTRAINT PK_BTCTB001 PRIMARY KEY (ID_USUARIO);

ALTER TABLE BTCTB002_DESTINO
	MODIFY COLUMN ID_DESTINO INT AUTO_INCREMENT,
    ADD CONSTRAINT PK_BTCTB002 PRIMARY KEY (ID_DESTINO);

ALTER TABLE BTCTB003_RESERVA
	MODIFY COLUMN ID_RESERVA INT AUTO_INCREMENT,
    ADD CONSTRAINT PK_BTCTB003 PRIMARY KEY (ID_RESERVA),
    ADD CONSTRAINT FK01_BTCTB001_BTCTB003 FOREIGN KEY (ID_USUARIO)
		REFERENCES BTCTB001_USUARIO (ID_USUARIO)
			ON DELETE CASCADE,
	ADD CONSTRAINT FK02_BTCTB002_BTCTB003 FOREIGN KEY (ID_DESTINO)
		REFERENCES BTCTB002_DESTINO (ID_DESTINO)
			ON DELETE CASCADE;